# Template config, need to change dump_dir, data.root_dir and data.tokenizer.path

dump_dir: "out"
name: "debug"
steps: 1000
probe_freq: 100
seed: 777
optim:
    lr: 3e-4
    warmup: 2000
    lr_min_ratio: 0.000001
    clip: 10.0

distributed:
    fsdp_type: no_shard
    compile: true
    model_dtype: bf16
    matmul_allow_tf32: false
    selective_activation_checkpointing: false
    tp_size: 1
    spawn_method: spawn

model:
    dim: 512
    n_layers: 4
    n_heads: 4

data:
    root_dir: data/
    sources:
        minipile_shuffled: 1.0
    batch_size: 1
    prefetch_size: 64
    seq_len: 512
    n_views: 2
    load_async: true
    tokenizer:
        name: tiktoken
        path: tokenizer/r50k_base.tiktoken

profiling:
    run: true

checkpoint:
    dump:
        every: 100
        keep: 1
    eval:
        every: 100
        keep: 1

logging:
    freq: 10

eval:
    generator:
        max_tokens: 8192
        dtype: bf16
        temperature: 1.0
        top_p: 0.95
    harness:
        tasks:
            - hellaswag
            - piqa
            - task: nq_open
              num_fewshot: 5
    validation:
        max_steps: 100
